#!/bin/bash
# chkconfig: 2345 95 20
# description: mount vm shared folder on boot
# mount vm shared folder on boot
# processname: mountshareddir
#5 - chkc

#move (mv) to /etc/rc.local for vm

#name of shared folder
start(){
    sharename="share"

    sudo mkdir /mnt/$sharename
    sudo chmod 777 /mnt/$sharename

#might need to be vboxfs
    sudo mount -t vboxsf -o uid=1000,gid=1000 $sharename /mnt/$sharename

    ln -s /mnt/$sharename $HOME/Desktop/$sharename
}
start
START=10